data-directory: data/montserrat
output-directory: out
downsample: 4
style: sunshine-animation
style-args:
  datetime-start: 2026-01-08T08:00:00+02:00
  datetime-end: 2026-01-08T19:00:00+02:00
  frames: 96
  duration: 4
  subsampling-level: 2