data-directory: data/montserrat
output-directory: out
downsample: 16
style: sunshine-animation
style-args:
  sun-azimuth-start: 180
  sun-altitude-start: 45
  sun-azimuth-end: 270
  sun-altitude-end: 5
  frames: 120
  duration: 5
  subsampling-level: 2