data-directory: data/barcelona
output-directory: out
downsample: 4
style: sunset-animation
style-args:
  sun-azimuth: 180
  sun-altitude: 45
  sun-azimuth-end: 270
  sun-altitude-end: 5
  frames: 120
  duration: 5
  subsampling-level: 2