[project]
name = "elevation"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pillow>=12.3.0",
    "pyproj>=3.8.0",
    "pyyaml>=6.0.3",
    "scipy>=1.18.1",
]

[project.scripts]
display = "elevation.__main__:main"

[tool.setuptools]
packages = ["elevation"]

[tool.scikit-build]
build-dir = "build"

[tool.uv]
no-build-isolation-package = ["elevation"]

[dependency-groups]
dev = ["pybind11", "scikit-build-core", "setuptools"]

[build-system]
requires = ['setuptools', "scikit-build-core", "pybind11"]
build-backend = "scikit_build_core.build"
